# Generated by Django 3.2.3 on 2024-09-18 17:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Уникальный username', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username')),
                ('first_name', models.CharField(help_text='Имя пользователя', max_length=150, verbose_name='Name')),
                ('last_name', models.CharField(help_text='Фамилия пользователя', max_length=150, verbose_name='Last name')),
                ('email', models.EmailField(help_text='Адрес электронной почты', max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(blank=True, choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=120, verbose_name='Role')),
                ('avatar', models.ImageField(blank=True, help_text='Картинка закодированная в Base64', upload_to='users/', verbose_name='Main foto')),
                ('groups', models.ManyToManyField(blank=True, related_name='baseuser_set', to='auth.Group')),
            ],
            options={
                'verbose_name': 'Пользователь',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь к подпискам',
            },
        ),
        migrations.AddField(
            model_name='baseuser',
            name='subscription',
            field=models.ManyToManyField(db_index=True, related_name='_registration_baseuser_subscription_+', through='registration.UserSubscription', to=settings.AUTH_USER_MODEL, verbose_name='User subscriptions'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='baseuser_set', to='auth.Permission'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(fields=('user', 'subscription'), name='unique_user_subscription'),
        ),
    ]
