# Generated by Django 3.2.3 on 2024-09-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_baseuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
