# Generated by Django 3.2.3 on 2024-09-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_auto_20240919_0634"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseuser",
            options={
                "ordering": ("date_joined",),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="usersubscription",
            options={
                "verbose_name": "Подписки пользователя",
                "verbose_name_plural": "Подписки пользователя",
            },
        ),
    ]
