# Generated by Django 3.2.3 on 2024-09-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тэги для группирования рецептов', max_length=32, verbose_name='Tag')),
                ('slug', models.SlugField(help_text='Slug тэга', max_length=32, unique=True, verbose_name='Slug')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
    ]
